### ISSUE TITLE
Please tag this repository

### ISSUE THREAD

**Issue by aviau** [sasha-s/go-deadlock#1]
Hello,

Could you please tag this repository?

I am the Debian Maintainer for this project and tags would help Debian keep up with new releases/bugfixes.

See:
- http://semver.org/
- http://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by sasha-s** [comment]
Done. 
https://github.com/sasha-s/go-deadlock/releases/tag/v0.1.0
