### ISSUE TITLE
Bug in 1595213edefa28ca5047b00340c63557f9c051d0

### ISSUE THREAD

**Issue by tsachiherman** [sasha-s/go-deadlock#19]
In the above change, you introduce a bug : 

Instead of getting the callers for the goroutine which was calling the lock, you exchanged that with the monitoring goroutine.
i.e. this is wrong :
```
fmt.Fprintf(Opts.LogBuf, "goroutine %v lock %p\n", goid.Get(), ptr)
printStack(Opts.LogBuf, callers(2))
```

**Comment by sasha-s** [comment]
https://github.com/sasha-s/go-deadlock/commit/00ee193ea4a32e0dea6c837f4fa6416c12242cc8
