### ISSUE TITLE
Support Go 1.23

### ISSUE THREAD

**Issue by linkdata** [sasha-s/go-deadlock#34]
Go 1.23 breaks older versions of github.com/petermattis/goid, including the one you're currently using.

I suggest you add go1.23 to your testing matrix and possibly also add a runtime init test that checks if the goid in use is working correctly or not.

Feel free to copy relevant bits from my fork: https://github.com/linkdata/deadlock

**Comment by sasha-s** [comment]
added go 1.23, will consider doing the runtime checks separately. 
Thanks.
